apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-minecraft
  annotations:
    kubernetes.io/ingress.class: minecraft
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: minecraft
          servicePort: 80
